Math Magicians : Add Calculator design
AnicetFantomas/Math_Magicians pull request #2
Opened 2022-04-26 20:10 UTC by AnicetFantomas

In this pull request we performed :

- The use of components in React

2022-04-26 20:36 UTC, codepantha requested changes
Hi @AnicetFantomas 👋, 

## STATUS: REQUESTED CHANGES ♻️ 

Good job so far! 👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/3ohzdQDcPFbBI3MhAk/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Consider:

- [ ] Creating a reusable `<Button>` component for your Calculator. This will make your project better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 20:36 UTC, codepantha commented on src/components/calculator.js
> +      </div>
- [ ] Please make your Calculator component a class-based component 🙏

2022-04-26 20:36 UTC, codepantha commented on src/App.js
>    return (
- [ ] Please make your App component a  class-based component 🙏

2022-04-26 20:36 UTC, codepantha commented on src/components/calculator.js
> +        <button type="button" className="button operation">/</button>
- [ ] Please model your styling according to the provided template 👇 
### Your Design
![image](https://user-images.githubusercontent.com/46839548/165387700-9da47ad3-ddf9-4a08-a875-c8c397dd8b06.png)
### Given Design
![image](https://user-images.githubusercontent.com/46839548/165387544-738c0e85-96ee-45c4-99b1-88a81fc01ba6.png)

2022-04-27 08:46 UTC, ShoiraTa approved these changes
## **STATUS: APPROVED  🟢 ** 
------
### Hi @AnicetFantomas , 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-04 16:20 UTC, merged